apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: 01-bgp-peering-policy
spec:
  virtualRouters:
    - localASN: 64513
      exportPodCIDR: false
      serviceSelector:
        # Export all services
        matchExpressions:
          - operator: NotIn
            key: dummy
            values:
              - dummy
      neighbors:
        - peerAddress: "10.28.100.1/32"
          peerASN: 64512
          connectRetryTimeSeconds: 120
          holdTimeSeconds: 30
          keepAliveTimeSeconds: 30
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
