namespace: kube-system

helmCharts:
- name: cilium
  releaseName: cilium
  version: 1.15.2
  repo: https://helm.cilium.io/
  includeCRDs: true
  valuesInline:
    tunnel: geneve
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList:
        - "172.18.0.0/16"
    hubble:
      enabled: false

