namespace: kube-system

resources:
  - bgppeeringpolicy.yaml
  - ciliumloadbalancerippool.yaml

helmCharts:
  - name: cilium
    releaseName: cilium
    version: 1.15.4
    repo: https://helm.cilium.io/
    includeCRDs: true
    valuesFile: values.yaml
    valuesMerge: override
