namespace: victoria-metrics

resources:
  - namespace.yaml
  - vmcluster.yaml

helmCharts:
  - name: victoria-metrics-operator
    releaseName: victoria-metrics-operator
    version: 0.30.1
    repo: https://victoriametrics.github.io/helm-charts/
    namespace: victoria-metrics
    includeCRDs: true
    valuesFile: values.yaml
    valuesMerge: override
