namespace: external-secrets

resources:
- namespace.yaml

helmCharts:
- name: external-secrets
  releaseName: external-secrets
  version: 0.9.15-2
  repo: https://charts.external-secrets.io
  namespace: external-secrets
  includeCRDs: true

