namespace: grafana

resources:
- namespace.yaml

helmCharts:
- name: grafana
  releaseName: grafana
  version: 7.3.9
  repo: https://grafana.github.io/helm-charts
  namespace: grafana
  includeCRDs: true

