namespace: grafana

resources:
- namespace.yaml

helmCharts:
- name: grafana
  releaseName: grafana
  version: 7.3.9
  repo: https://grafana.github.io/helm-charts
  namespace: grafana
  includeCRDs: true
  valuesInline:
    ingress:
      enabled: true
      hosts:
      - grafana.mofuwa.net
      ingressClassName: nginx

