apiVersion: v1
kind: Namespace
metadata:
  name: palworld
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: palworld-settings
  namespace: palworld
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    template: {}
  data:
  - secretKey: PalWorldSettings.ini
    remoteRef:
      key: PalWorldSettingsIni
      property: PalWorldSettings.ini
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: palworld-server
  namespace: palworld
spec:
  replicas: 1
  serviceName: palworld
  selector:
    matchLabels:
      app: palworld
  template:
    metadata:
      labels:
        app: palworld
    spec:
      nodeSelector:
        kubernetes.io/hostname: yveltal
      containers:
      - name: palworld
        image: cm2network/steamcmd:latest
        volumeMounts:
        - name: data
          mountPath: /home/steam/Steam
        - name: config
          mountPath: /config
        - name: settings
          mountPath: /settings
        command:
        - /bin/bash
        - /config/init-script.sh
        tty: true
      volumes:
      - name: config
        configMap:
          name: palworld-config
      - name: settings
        secret:
          secretName: palworld-settings
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: local-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: palworld-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/palworld
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - yveltal
---
apiVersion: v1
kind: Service
metadata:
  name: palworld
  namespace: palworld
spec:
  selector:
    app: palworld
  ports:
    - port: 8211
      targetPort: 8211
      protocol: UDP
      name: palworld
    - port: 25575
      targetPort: 25575
      protocol: TCP
      name: rcon
  type: LoadBalancer
