apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    creationPolicy: Owner
  data:
  - secretKey: apiToken
    remoteRef:
      key: Infra-Cluster-External-DNS-Cloudflare-API-Key
      property: credential
  - secretKey: email
    remoteRef:
      key: Infra-Cluster-External-DNS-Cloudflare-API-Key
      property: username
