serviceAccount:
  create: true
policy: sync
registry: txt
txtOwnerId: k8s
provider:
  name: cloudflare
sources:
  - ingress
domainFilters:
  - mofuwa.net
#extraArgs:
#  - "--cloudflare-proxied"
#  - "--cloudflare-dns-records-per-page=5000"
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-secrets
        key: apiToken
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare-secrets
        key: email
extraVolumes:
  - name: cloudflare-secrets
    secret:
      secretName: cloudflare-secrets
