namespace: kube-system

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  version: 1.14.4
  repo: https://charts.jetstack.io
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    installCRDs: true
