namespace: cert-manager

resources:
- namespace.yaml
- issuer.yaml

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  version: 1.14.4
  repo: https://charts.jetstack.io
  namespace: cert-manager
  includeCRDs: true
  valuesInline:
    installCRDs: true
