apiVersion: v1
kind: Namespace
metadata:
  name: palog
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: palworld-rcon-creds
  namespace: palog
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    template: {}
  data:
    - secretKey: RCON_PASSWORD
      remoteRef:
        key: PalWorldRCONCreds
        property: password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: palog
  namespace: palog
spec:
  replicas: 1
  serviceName: palog
  selector:
    matchLabels:
      app: palog
  template:
    metadata:
      labels:
        app: palog
    spec:
      containers:
        - name: palog
          image: ghcr.io/miscord-dev/palog:v0.0.5
          envFrom:
            - secretRef:
                name: palworld-rcon-creds
          env:
            - name: RCON_ENDPOINT
              value: palworld.palworld.svc.cluster.local:25575
