namespace: argocd

resources:
- namespace.yaml
- projects.yaml
- 'https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml'

patches:
- path: argocd-cm.yaml
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: argocd-server
      namespace: argocd
    spec:
      type: LoadBalancer
      ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
      - name: https
        port: 443
        protocol: TCP
        targetPort: 8080
  target:
    kind: Service
    labelSelector: "app.kubernetes.io/name=argocd-server"
