apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    template: {}
    creationPolicy: Merge
  data:
  - secretKey: oidc.auth0.clientID
    remoteRef:
      key: ArgoCD-OIDC-Credential
      property: username
  - secretKey: oidc.auth0.clientSecret
    remoteRef:
      key: ArgoCD-OIDC-Credential
      property: credential
  - secretKey: oidc.auth0.issuer
    remoteRef:
      key: ArgoCD-OIDC-Credential
      property: issuer
