namespace: otel-collector

resources:
- namespace.yaml

helmCharts:
- name: opentelemetry-collector
  releaseName: otel-collector-cluster
  version: 0.89.0
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  includeCRDs: false
  valuesInline:
    mode: deployment
    replicaCount: 1
    image:
      repository: "otel/opentelemetry-collector-contrib"
    config:
      receivers:
        prometheus:
          config:
            scrape_configs:
            - job_name: 'otelcol'
              scrape_interval: 10s
              static_configs:
              - targets: ['0.0.0.0:8888']
              metric_relabel_configs:
              - source_labels: [__name__]
                regex: '.*grpc_io.*'
                action: drop
      exporters:
        prometheusremotewrite:
          endpoint: "http://vminsert-main.victoria-metrics.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: []
            exporters: [prometheusremotewrite]
- name: opentelemetry-collector
  releaseName: otel-collector
  version: 0.89.0
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  includeCRDs: false
  valuesInline:
    mode: daemonset
    image:
      repository: "otel/opentelemetry-collector-contrib"
    config:
      exporters:
        prometheusremotewrite:
          endpoint: "http://vminsert-main.victoria-metrics.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: []
            exporters: [prometheusremotewrite]

