namespace: otel-collector

resources:
- namespace.yaml

helmCharts:
- name: opentelemetry-collector
  releaseName: otel-collector-cluster
  version: 0.89.0
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  includeCRDs: false
  valuesInline:
    mode: deployment
    replicaCount: 1
    image:
      repository: "otel/opentelemetry-collector-contrib"
    presets:
      clusterMetrics:
        enabled: true
    config:
      exporters:
        prometheusremotewrite:
          endpoint: "http://vminsert-main.victoria-metrics.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: []
            exporters: [prometheusremotewrite]

